### ISSUE TITLE
Parent cannot be a child of itself

### ISSUE THREAD

**Issue by rtorino** [overlookmotel/sequelize-hierarchy#10]
Initially I have these data:

``` javascript
[
  {
    "id": "36e36228-080c-492e-a583-f5521005d446",
    "name": "Lose 10kg",
    "status": null,
    "dueDate": null,
    "progress": 0,
    "description": null,
    "createdAt": "2015-02-19T10:34:27.663Z",
    "updatedAt": "2015-02-19T10:34:27.663Z",
    "deletedAt": null,
    "hierarchyLevel": 1,
    "parentId": null,
    "children": [
      {
        "id": "a5c13e20-883f-4ca7-a957-b021b6ae5f45",
        "name": "Tracker 1",
        "status": null,
        "dueDate": null,
        "progress": 0,
        "description": null,
        "createdAt": "2015-02-19T10:34:57.194Z",
        "updatedAt": "2015-02-19T10:34:57.194Z",
        "deletedAt": null,
        "hierarchyLevel": 2,
        "parentId": "36e36228-080c-492e-a583-f5521005d446"
      }
    ]
  }
]
```

I'm trying to swap so that `Lose 10kg` would become a child of `Tracker 1` then I got `SequelizeHierarchy` error that says `Parent cannot be a child of itself`. My understanding of the error is you cannot set the parent as a child of itself. That means for me that I can't set the `parentId` to the same value of `id`. If my understanding is correct, can we support the feature to be able to swap parent and child just in case I made a mistake in creating these objects?

**Comment by overlookmotel** [comment]
Hi.

Sorry for slow reply. Computer stuff isn't my day job, so I often get unfortunately side-tracked away from maintaining these modules.

I'm afraid that setting a parent as child of itself wouldn't work - it doesn't make sense to have a circular relation in a hierarchy. In other structure models this might be fine, but the hierarchy model requires that each item has a parent which is below it, and children above, and children can't also be parents.

But still, what you want to do - swapping the parent with the child - is possible.

You'd have to do it in two steps:

1. Set parentId of `Tracker 1` to `null` (so now `Lose 10kg` and `Tracker 1` are siblings)
2. Set parent of `Lose 10kg` to `Tracker 1`

Now the two items have swapped places, and it won't trigger the `Parent cannot be a child of itself` error.

Does that make sense?

**Comment by rtorino** [comment]
@overlookmotel, this makes sense. Thanks.
