### ISSUE TITLE
I found another simple solution could you take a look?

### ISSUE THREAD

**Issue by drinkjava2** [overlookmotel/sequelize-hierarchy#104]
Could you take a look of this:  
[https://github.com/drinkjava2/Multiple-Columns-Tree](https://github.com/drinkjava2/Multiple-Columns-Tree)
Use 2 extra columns: (sorted) line and depth, will easily do query/delete/insert operations for child/sibling/parent nodes only with 1 single SQL.

**Comment by mentos1386** [comment]
There is also another way. Which uses 1 column for all the data.
https://bojanz.wordpress.com/2014/04/25/storing-hierarchical-data-materialized-path/

**Comment by overlookmotel** [comment]
Hi @drinkjava2 and @mentos1386.

Yes, both of those are alternative methods for storing hierarchy data in a relational DB.

I chose the method that sequelize-hierarchy uses for 3 reasons:
1. It has no limit on depth of hierarchy (unlike materialized path method, for example)
2. It's fairly simple
3. Quick for reads

Some other archtectures are valid and may be better for some use cases. If you'd like to submit a PR to implement any of these as an additional option, I'd be happy to consider it. But for my purposes, the current architecture works fine and I don't have time to implement anything else.

Closing this issue, but if you do want to work on a PR, please reopen and we can discuss.
