### ISSUE TITLE
Field createdAt and updatedAt fields are empty.

### ISSUE THREAD

**Issue by novajohn** [overlookmotel/sequelize-hierarchy#112]
The module does not populate **createdAt** and **updatedAt** fields in the hierarchy table '<model name plural>ancestors'. In some cases it could cause validation issues since these fields do not have default values.

**Comment by overlookmotel** [comment]
By default, the hierarchy table is created with no `createdAt` or `updatedAt` fields, using the `timestamps: false` option. See here: https://github.com/overlookmotel/sequelize-hierarchy/blob/master/lib/modelExtends.js#L111

There is no point in timestamp fields in the hierarchy table as all the data in the hierarchy table is denormalized - i.e. it's just an alternative representation of the data in the main table.

But are you finding the hierarchy table is created with timestamp fields? If so, please let me know which version of sequelize-hierarchy and sequelize you're using.

**Comment by novajohn** [comment]
Thank you for quick response. You are completely right. I'm maintaining the code where the hierarchy table is created manually. Hence the question arises of how to ask of force the module to create/sync the hierarchy table directly in a database automatically?

**Comment by overlookmotel** [comment]
If you define a table with `hierarchy: true` option, or call `model.isHierarchy()`, sequelize-hierarchy will define the hierarchy table automatically. Then you need to call `sequelize.sync()` for the actual table in the DB to be created.

If you want to create the hierarchy table manually, that's fine, but just do so with `timestamps: false` option so it doesn't create the timestamp fields.

I think this should fix your problem, so closing this issue. But feel free to re-open if it's not solved.
