### ISSUE TITLE
StructureId must be unique

### ISSUE THREAD

**Issue by freenetwork** [overlookmotel/sequelize-hierarchy#116]
[{StructureId must be unique","type":"unique violation","path":"StructureId","value":"2"},{"message":"ancestorId must be unique","type":"unique violation","path":"ancestorId","value":"1"}]

Structure.js

-=-=-=-=-=-=-=-=-

```js
"use strict";
module.exports = function(sequelize, DataTypes) {
  
  var Structure = sequelize.define("Structure", {
    id: {
      type: DataTypes.INTEGER,
      autoIncrement: true,
      primaryKey: true
    },
    name: {
      type: DataTypes.STRING
    }
  },
    timestamps: false,
    hierarchy: true,
  });
  Structure.isHierarchy();
  return Structure;
};
```

{"name":"SequelizeUniqueConstraintError","message":"Validation error","errors":[{"message":"StructureId must be unique","type":"unique violation","path":"StructureId","value":"2"},{"message":"ancestorId must be unique","type":"unique violation","path":"ancestorId","value":"1"}],"fields":{"StructureId":"2","ancestorId":"1"},"parent":{"name":"error","length":243,"severity":"ERROR","code":"23505","detail":"Key (\"StructureId\", \"ancestorId\")=(2, 1) already exists.","schema":"public","table":"Structuresancestors","constraint":"Structuresancestors_pkey","file":"nbtinsert.c","line":"402","routine":"_bt_check_unique","sql":"INSERT INTO \"Structuresancestors\" (\"StructureId\",\"ancestorId\") VALUES (2,1);"},"original":{"name":"error","length":243,"severity":"ERROR","code":"23505","detail":"Key (\"StructureId\", \"ancestorId\")=(2, 1) already exists.","schema":"public","table":"Structuresancestors","constraint":"Structuresancestors_pkey","file":"nbtinsert.c","line":"402","routine":"_bt_check_unique","sql":"INSERT INTO \"Structuresancestors\" (\"StructureId\",\"ancestorId\") VALUES (2,1);"},"sql":"INSERT INTO \"Structuresancestors\" (\"StructureId\",\"ancestorId\") VALUES (2,1);"}

conference_dev=> select * from "Structuresancestors" ;
 StructureId | ancestorId
-------------+------------
           2 |          1
           3 |          1
           4 |          1
           5 |          1

**Comment by overlookmotel** [comment]
Try removing the line `Structure.isHierarchy();`. You already used the `hierarchy: true` option. You only need to do one or the other.

Please let me know if that works.

**Comment by freenetwork** [comment]
Nice! This, work! Thanks!

**Comment by overlookmotel** [comment]
Great!
