### ISSUE TITLE
TypeError: defineCall is not a function

### ISSUE THREAD

**Issue by MrDHat** [overlookmotel/sequelize-hierarchy#122]
I am getting this error after importing the module:

```
 TypeError: defineCall is not a function
     at Sequelize.import (/app/node_modules/sequelize/lib/sequelize.js:691:30)
     at fs.readdirSync.filter.forEach (/app/src/db/models/index.js:22:35)
     at Array.forEach (native)
     at Object.<anonymous> (/app/src/db/models/index.js:21:4)
     at Module._compile (module.js:571:32)
     at Object.Module._extensions..js (module.js:580:10)
     at Module.load (module.js:488:32)
     at tryModuleLoad (module.js:447:12)
     at Function.Module._load (module.js:439:3)
     at Module.require (module.js:498:17)
     at require (internal/module.js:20:19)
     at Object.<anonymous> (/app/src/controllers/user.js:1:74)
     at Module._compile (module.js:571:32)
     at Object.Module._extensions..js (module.js:580:10)
     at Module.load (module.js:488:32)
     at tryModuleLoad (module.js:447:12)
```

`db/models/index.js`
```js
const fs = require('fs');
const path = require('path');
const Sequelize = require('sequelize-hierarchy')();

const basename = path.basename(module.filename);
const env = process.env.NODE_ENV || 'development';
const Config = require(`${__dirname}/../../sequelizeConfig.js`)[env]; // eslint-disable-line import/no-dynamic-require
const db = {};
let sequelize;

if (Config.use_env_variable) {
  sequelize = new Sequelize(process.env[Config.use_env_variable]);
} else {
  sequelize = new Sequelize(Config.database, Config.username, Config.password, Config);
}


fs
  .readdirSync(__dirname)
  .filter(file => (file.indexOf('.') !== 0) && (file !== basename) && (file.slice(-3) === '.js'))
  .forEach((file) => {
    const model = sequelize.import(path.join(__dirname, file));
    db[model.name] = model;
  });

Object.keys(db).forEach((modelName) => {
  if (db[modelName].associate) {
    db[modelName].associate(db);
  }
});

db.sequelize = sequelize;
db.Sequelize = Sequelize;

module.exports = db;

```

And this is what my model looks like:
```js
module.exports = (sequelize, DataTypes) => {
  const schema = sequelize.define('ProductCategory', {
    id: {
      type: DataTypes.UUID,
      primaryKey: true,
      defaultValue: DataTypes.UUIDV4,
      allowNull: false,
    },
    name: {
      type: DataTypes.STRING,
    },
    // Hierarchy plugin components
    hierarchyLevel: {
      type: DataTypes.INTEGER.UNSIGNED,
    },
    parentId: {
      type: DataTypes.UUID,
      references: {
        model: 'ProductCategory',
        key: 'id',
      },
    },
  }, {
    tableName: 'ProductCategory',
    freezeTableName: true,
    hierarchy: true,
    camelThrough: true,
  });

  return schema;
};

```

Not sure what is going on.

**Comment by overlookmotel** [comment]
Sorry for slow reply.

It looks to me that this is not related to `sequelize-hierarchy`. The line where the error is being thrown is in Sequelize itself `at Sequelize.import (/app/node_modules/sequelize/lib/sequelize.js:691:30)`.

I would suggest to latest version of Sequelize and if it still fails raise an issue on Sequelize repo.

Closing this issue as I believe it to be unrelated, but feel free to reopen if you disagree.

**Comment by murnun** [comment]
In my case, it was the `index.js` file created inside my `models` directory by `sequelize CLI` when i ran its `init` command. After simply removing this file, the error went away. This still seems like a conflicting behavior between the CLI and how sequelize imports models; and I'd like to learn why this is so -- or if it's more of an issue between incompatible versions of `sequelize` & `postgres`and other accompanying tools. If anyone has more insight, please kindly do let me know here.

**Comment by alvaro-paco** [comment]
This is a CLI issue and must be fixed. This occurs when you make a module.exports in a object like module.exports = {...}. If you make module.exports = () =>{} the error gone but the Sequelize cannot import you module. To correct this bug declare you models as Address.js:

`/**
 * Address.js
 *
 * @description :: TODO: You might write a short summary of how this model works and what it represents here.
 * @docs        :: http://sailsjs.org/documentation/concepts/models-and-orm/models
 */

module.exports = () =>{
  return {
    attributes: {
      number: {
        type: Sequelize.INTEGER,
        allowNull: false
      },
      street: {
        type: Sequelize.STRING,
        allowNull: false
      },
      city: {
        type: Sequelize.STRING,
        allowNull: false
      },
      province: {
        type: Sequelize.STRING,
        allowNull: true
      },
      postalCode: {
        type: Sequelize.STRING,
        field: 'postal_code',
        unique: true,
        allowNull: false
      },
      country: {
        type: Sequelize.STRING,
        unique: true,
        allowNull: false
      }
    },
    associations: function() {
      Address.belongsTo(Account, {
        as: 'account',
        foreignKey: {
          name: 'account_id',
          allowNull: false
        }
      });
    },
    options: {
      tableName: 'address',
      underscored: true,
      classMethods: {},
      instanceMethods: {
        toJSON: function() {
          var obj = this.dataValues;
          obj.createdAt = obj.created_at;
          obj.updatedAt = obj.updated_at;
          delete obj.created_at;
          delete obj.updated_at;
          return obj;
        }
      },
      hooks: {}
    }
  }
};
`
