### ISSUE TITLE
Documentation: More detail on creating hierarchies and mutating them, including bulkCreate

### ISSUE THREAD

**Issue by Kumfert** [overlookmotel/sequelize-hierarchy#123]
I'm trying to incorporate sequelize-hierarchy into my code, but simply adding parentId to bulkCreate  is breaking my unit tests.  Here's a few questions I found myself asking as I was trying to figure out what's going on, none of which I could find answers for in the README.md

1. How do I bulkCreate? just include parentId? 
2. Must parents be created before children? 
3. Do I need to call rebuildHierarchy() after bulkCreate()?   
4. There are accessors for getting parent, children, ancestors and descendants, what about setters?
5.  What's the recommended/safest/most-performant way to promote or demote an item in the hierarchy?

**Comment by overlookmotel** [comment]
Hi @Kumfert.

Sorry for slow reply. Have been away.

I have just updated the README to hopefully answer all of your questions. Please have a look and let me know if it's still not clear.

Q5: Nothing special about it. Just update the `parentId` of a record to it's new parent. The hierarchy will be restructured accordingly, including promoting/demoting all children.

**Comment by overlookmotel** [comment]
Closing this issue for now. Please reopen it if you feel the README still doesn't answer your questions.

**Comment by muskan21** [comment]
Hi

I would like to know how to use setters like addChild.
It's unclear in the documentation.
Anyone?

**Comment by overlookmotel** [comment]
@muskan21 This is standard Sequelize stuff, not specific to sequelize-hierarchy. Please see the main Sequelize docs.
