### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by atlantageek** [overlookmotel/sequelize-hierarchy#125]
When I rebuild my hierarchy I get this error.
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

My hierarchy is large Im a 274,611 records spread out over 8 levels of hierarchy.  Do you have a suggestion for me to resolve this.

**Comment by overlookmotel** [comment]
Hi @atlantageek.

Hmm yes the `rebuildHierarchy` method has not been written with large tables in mind.

The way it works is to go through the hierarchy level by level, and for each level it loads into memory the entire set of records for that level. So when the table is as big as yours, I'm not surprised the process runs out of memory.

Obviously, this is a fault in the code. However, I took this shortcut as `rebuildHierarchy` should never need to be used in usual circumstances.

It could be re-written to avoid this problem by executing raw SQL statements. However, these would need to be different for each database dialect, so it'd be a pain to write and maintain.

Why are you using `rebuildHierarchy()`? You already have a table full of data and want to create a hierarchy from it?

Please let me know and I'll suggest a workaround.

**Comment by atlantageek** [comment]
2 places.
1. In the import of the hierarchy. Honestly I might not need it here. Im using a function called upsertWithReturn from sequelize and it might be populating the ancestors table properly.  I will have to check.
2. I store statistics in my hierarchy that gets recalculated every 10 minutes. I do this in clone of the organization table. When its complete the ancestors table gets dropped. The new hierarchy table swaps with the old table and the rebuild hierarchy function is run.  This was to minimize down time.

**Comment by overlookmotel** [comment]
1. I assume `upsertWithReturn` (whatever that is - can't find any mention of it in the docs!) will call `create` or `update` internally and so the hierarchy table will be updated automatically. So you should not need rebuildHierarchy. Please let me know. If `upsertWithReturn` isn't updating the hierarchy table then it should be - it's a bug which needs fixing.

2. Sorry, I don't get what you're doing. Can you explain it a bit more step-by-step to me?

**Comment by overlookmotel** [comment]
Closing as no response from OP.
