### ISSUE TITLE
Best approach to initialize

### ISSUE THREAD

**Issue by aaronovz1** [overlookmotel/sequelize-hierarchy#132]
What is the best way to initialize an initial set of nested categories? 

Eg.
```
1
 1.1
 1.2
  1.2.1
  1.2.2
2
 2.1
 2.2
  2.2.1
  2.2.2
```

**Comment by deksden** [comment]
If data is as simple and small as this, just write some script to insert via Sequelize.

If data is large, use database features to bulk load data, then use categoriesModel.rebuildHierarchy() - see readme. please note that rebuilding hierarchy should load a lot of data into memory, so be prepared!

**Comment by aaronovz1** [comment]
I would like to use javascript and build it when the app first loads and only once. Is the below method the right way or is there a more practical approach to link the relationships? Can you provide an example?

```javascript
models.Category.find({where: {name: "C1.0"}}).bind(this).then(function(cat){
    if (cat) {
      return cat;
    } else {
      return models.Category.bulkCreate([
        {name: "C1.0"},
        {name: "C2.0"},
        {name: "C3.0"},
      ]).then(function(cats){
        return models.Category.bulkCreate([
          {name: "C1.1", parent_id: 1},
          {name: "C2.1", parent_id: 2},
          {name: "C3.1", parent_id: 3},
        ]);
      });
    }
  });
```

**Comment by deksden** [comment]
Generally - yes, this is ok. 

But i see some problems with your code: you can not be 100% sure if parent_id:1 will point to C1.0 item, so you need some way to know id of C1.0. Maybe it will be better to store idol C1.0 after creating. bulkCreate will not return created instances, so it will be better to create root objects one by one and remember id's of created objects to use as parent_id.

Side note: not sure why you want bind(this)

**Comment by overlookmotel** [comment]
As @deksden says, you need to make sure your `parent_id`s are pointing to the right `id`s. But the principle is correct - you need to insert the records level by level i.e. root level first, then children of the root level items, then children of the children etc.

Does this answer your question? When you feel it's answered, please close the issue.

**Comment by overlookmotel** [comment]
Haven't heard from you so assuming this is solved and closing the issue. Thanks @deksden for answering it.
