### ISSUE TITLE
Sequelize-heirarchy with migrations

### ISSUE THREAD

**Issue by Gazfay** [overlookmotel/sequelize-hierarchy#135]
Hi! How i can use this lib with sequelize migrations, models created by sequelize-cli?

**Comment by overlookmotel** [comment]
Hi @Gazfay. Can you please expand a bit on what you're trying to do? I'm not sure how to answer your question with the info you've given.

**Comment by alisherafat01** [comment]
@overlookmotel 
how to create tables which is required by this lib?
i'm using sequelize-cli and migrations to create tables manually

**Comment by overlookmotel** [comment]
`sequelize.sync()` will create the tables for you.

If you don't want to use `.sync()` I'd suggest setting up a small test database and just `.sync()` on that so you can see what the tables should look like.

There are too many options which affect the definition of the tables, so it's not easy to give you example SQL.
