### ISSUE TITLE
Can not query ancestors/children's associations?

### ISSUE THREAD

**Issue by giuem** [overlookmotel/sequelize-hierarchy#136]
I have a comment table which is hierarchy and every comment has an author(user). Now I want to query particular comments with their author as a nested tree, but I got an error `Not unique table/alias: 'children->user'`

## Define

``` javascript
const User = sequelize.define('user', {
    id: {
      type: Sequelize.INTEGER.UNSIGNED,
      primaryKey: true,
      autoIncrement: true,
    },
    username: {
      type: Sequelize.STRING,
    },
});

const Comment = sequelize.define('comment', {
    id: {
      type: Sequelize.INTEGER.UNSIGNED,
      primaryKey: true,
      autoIncrement: true,
    },
    // ...
});
Comment.isHierarchy();

Comment.associate = function() {
    Comment.belongsTo(User);
};

User.associate = function() {
    User.hasMany(Comment, { as: 'comments' });
};
```

## Query

``` javascript
Comment.findAll({
    where: {/* some conditions */},
    include:[{
        model: User,
    }, {
        model: Comment,
        as: 'descendents',
        hierarchy: true,
        include: [{
            model: User,
        }],
    }],
})
```

I'm using
```
"sequelize": "^4.4.2"
"sequelize-hierarchy": "^1.3.1"
Mysql: 5.7.16
```

**Comment by overlookmotel** [comment]
@giuem Thanks for detailed report.

I'm not able to reproduce.

I've made a test case here: https://github.com/overlookmotel/sequelize-hierarchy/blob/issue-136/test/issue136.test.js

It passed fine on my laptop. Currently running on Travis CI too: https://travis-ci.org/overlookmotel/sequelize-hierarchy/builds/269650144

Can you have a look please and see if test case differs from your non-working example?

**Comment by giuem** [comment]
Thanks for your test! I found that in my code, I made a variable `includeUser`
``` javascript
const includeUser = {
    model: User
}
```
And then find like in this way, the error comes out
``` javascript
Comment.findAll({
  include: [
    includeUser,
    {
      model: Comment,
      as: 'descendents',
      hierarchy: true,
      include: [ includeUser ]
    }]
}).then(function (comments) {
  console.log(comments)
});
```

**Comment by overlookmotel** [comment]
Sorry, I don't understand. Are you saying you have solved the issue?

**Comment by giuem** [comment]
Yes, I have solved it. But I don't know why my code can't run 😢
