### ISSUE TITLE
Typescript 

### ISSUE THREAD

**Issue by creadicted** [overlookmotel/sequelize-hierarchy#137]
Hello!
Is there any experience using sequelize plugins when the environment is typescript based? I have not found a solution so far. 
best

**Comment by overlookmotel** [comment]
I'm sorry but I have no knowledge of Typescript. I'll leave this issue open in case any other users do.

**Comment by creadicted** [comment]
Thank you for your reply. The whole plugin looks very beneficial. 
I try to create a @types file for the plugin. Maybe that will lead to something...

**Comment by LogansUA** [comment]
@overlookmotel I case you decided to do it, here's the [right way](https://github.com/DefinitelyTyped/DefinitelyTyped)

**Comment by EduardsE** [comment]
Did you get anywhere with this @creadicted ?

**Comment by creadicted** [comment]
I went to use TypeORM at the end. The hierarchy option is there directly integrated.

**Comment by EduardsE** [comment]
@creadicted We went with TypeORM at the beginning but soon after migrated to sequelize. We hit a lot of issues with TypeORM.

**Comment by creadicted** [comment]
@EduardsE I have not reached any major issues that gave me the reason to go back to sequelize. But I do very basic stuff with TypeORM and are happy so far. I also did not want to start a ORM fight :) 
That was just the reason I stopped this approach.

**Comment by overlookmotel** [comment]
Seemingly no interest in this, so closing.
