### ISSUE TITLE
Getting only descendents of an entity

### ISSUE THREAD

**Issue by ipelovski** [overlookmotel/sequelize-hierarchy#14]
Hi, thanks for updating the library to work with Sequelize v.3 - it works perfectly.

I have a question about querying data. Is there a way to get the descendents of an entity without getting the very entity. Right now I have this query:
```
Model.findAll({
	where: { id: ancestorId },
	include: [{
		model: Model,
		as: 'descendents'
	}]
});
```
which returns something like this:
```
[{
	"id": 5576,
	"hierarchyLevel": 1,
	"parentId": null,
	// more fields
	"descendents": [
		{
			"id": 5587,
			"hierarchyLevel": 2,
			"parentId": 5576,
			// more fields
		}, // more descendents
	]
}]
```
Is there a way to get the descendents list directly without the ancestor entity?

**Comment by overlookmotel** [comment]
If you already have a Sequelize Instance for the record you want to find descendents for, you can do:

```js
instance.getDescendents();
```

or:

```js
instance.getDescendents( { hierarchy: true } );
```


If you don't have the Instance, let me know - there might be a way to do it but I'd have to look at the code - I wrote it some time ago and can't remember!

**Comment by ipelovski** [comment]
Thanks for the quick answer. I have only the id in my method so I hoped there is a way to get the list directly.

**Comment by ipelovski** [comment]
I found what I should do here: https://github.com/sequelize/sequelize/issues/1775 -> https://github.com/sequelize/sequelize/commit/4887b84030caedb4d85d71c2afe9030954dd374a
The query should be:
```
Model.findAll({
	include: [{
		model: Model,
		as: 'descendents',
		through: {
			where: {
				ancestorId: ancestorId
			}
		}
	}]
});
```
Sorry for bothering you with this.
