### ISSUE TITLE
bulkCreate with associations?

### ISSUE THREAD

**Issue by corysimmons** [overlookmotel/sequelize-hierarchy#141]
Does sequelize-hierarchy support this? If so, could you explain how it works exactly (or add to README)?

Thank you 🙇

**Comment by overlookmotel** [comment]
Hi.

Can you possibly expand a bit on what you're trying to do? I don't quite understand what you mean by "bulkCreate with associations".

**Comment by corysimmons** [comment]
I have a parent table, `listings`, with a `hasMany` relationship to `listing_colors`. I'd like to be able to use Sequelize's `bulkCreate` to create listings with colors, but Sequelize doesn't support that out of the box.

I was wondering if your tool could help with that.

**Comment by overlookmotel** [comment]
Hi @corysimmons. Sorry for very slow reply.

I'm afraid this module won't help you with that. This module simply helps deal with tree-type hierarchical data structures. You should be able to do what you're trying to with Sequelize alone.
