### ISSUE TITLE
[BUG] Cannot read property 'underscoredIf'

### ISSUE THREAD

**Issue by Zero-Zheng** [overlookmotel/sequelize-hierarchy#142]
# error logs

> error: uncaughtException:Cannot read property 'underscoredIf' of undefined date=Mon Oct 02 2017 00:08:01 GMT+0800 (CST), pid=19754, uid=501, gid=20, cwd=/Users/zero/www/freshlinker, execPath=/usr/local/bin/node, version=v8.6.0, argv=[/usr/local/bin/node, /Users/zero/www/freshlinker/bin/www.js], rss=68435968, heapTotal=43167744, heapUsed=26580568, external=156061, loadavg=[1.86376953125, 3.01171875, 2.92333984375], uptime=22032, trace=[column=38, file=/Users/zero/www/freshlinker/node_modules/sequelize-hierarchy/lib/patches.js, function=module.exports, line=24, method=exports, native=false, column=16, file=/Users/zero/www/freshlinker/node_modules/sequelize-hierarchy/lib/index.js, function=module.exports, line=18, method=exports, native=false, column=31, file=/Users/zero/www/freshlinker/models/index.js, function=null, line=9, method=null, native=false, column=30, file=module.js, function=Module._compile, line=624, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=635, method=.js, native=false, column=32, file=module.js, function=Module.load, line=545, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=508, method=null, native=false, column=3, file=module.js, function=Module._load, line=500, method=_load, native=false, column=17, file=module.js, function=Module.require, line=568, method=require, native=false, column=18, file=internal/module.js, function=require, line=11, method=null, native=false, column=16, file=/Users/zero/www/freshlinker/helpers/ValidateHelper.js, function=null, line=5, method=null, native=false, column=30, file=module.js, function=Module._compile, line=624, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=635, method=.js, native=false, column=32, file=module.js, function=Module.load, line=545, method=load, native=false, column=12, file=module.js, function=tryModuleLoad, line=508, method=null, native=false, column=3, file=module.js, function=Module._load, line=500, method=_load, native=false, column=17, file=module.js, function=Module.require, line=568, method=require, native=false, column=18, file=internal/module.js, function=require, line=11, method=null, native=false, column=24, file=/Users/zero/www/freshlinker/app.js, function=null, line=101, method=null, native=false, column=30, file=module.js, function=Module._compile, line=624, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=635, method=.js, native=false, column=32, file=module.js, function=Module.load, line=545, method=load, native=false], stack=[TypeError: Cannot read property 'underscoredIf' of undefined,     at module.exports (/Users/zero/www/freshlinker/node_modules/sequelize-hierarchy/lib/patches.js:24:38),     at module.exports (/Users/zero/www/freshlinker/node_modules/sequelize-hierarchy/lib/index.js:18:16),     at Object.<anonymous> (/Users/zero/www/freshlinker/models/index.js:9:31),     at Module._compile (module.js:624:30),     at Object.Module._extensions..js (module.js:635:10),     at Module.load (module.js:545:32),     at tryModuleLoad (module.js:508:12),     at Function.Module._load (module.js:500:3),     at Module.require (module.js:568:17),     at require (internal/module.js:11:18),     at Object.<anonymous> (/Users/zero/www/freshlinker/helpers/ValidateHelper.js:5:16),     at Module._compile (module.js:624:30),     at Object.Module._extensions..js (module.js:635:10),     at Module.load (module.js:545:32),     at tryModuleLoad (module.js:508:12),     at Function.Module._load (module.js:500:3),     at Module.require (module.js:568:17),     at require (internal/module.js:11:18),     at Object.<anonymous> (/Users/zero/www/freshlinker/app.js:101:24),     at Module._compile (module.js:624:30),     at Object.Module._extensions..js (module.js:635:10),     at Module.load (module.js:545:32)]

# environment
node:v8.6.0
npm:5.3.0
os:10.11.6 (15G31) and Ubuntu 16.04 LTS
# Plugin
sequelize: > 4.10.1
sequelize-hierarchy:1.3.1

### Solve the problem
sequelize-hierarchy/lib/patches.js

 underscoredIf: {
          '^2.0.0': Sequelize.Utils._.underscoredIf,
          '>=3.0.0': Sequelize.Utils.underscoredIf
},

Replace:

underscoredIf: {
          '^2.0.0': Sequelize.Utils.underscoredIf,
          '>=3.0.0': Sequelize.Utils.underscoredIf
},

> I don't know if it affects Sequlize versions 2.x.x., But sequelize 2.0.4 Utils.js code 
_.mixin({
      includes: function(str, needle){
        if (needle === '') return true;
        if (str === null) return false;
        return String(str).indexOf(needle) !== -1;
      },
      camelizeIf: function(string, condition) {
        var result = string;

        if (condition) {
          result = Utils.camelize(string);
        }

        return result;
      },
      underscoredIf: function(string, condition) {
        var result = string;

        if (condition) {
          result = inflection.underscore(string);
        }

        return result;
      },
..... more

so i don't know.

**Comment by aaronovz1** [comment]
I see the same problem after updating Sequelize to 4.13.1

**Comment by deksden** [comment]
Here is more generic fix (in PR/comments): https://github.com/overlookmotel/sequelize-hierarchy/pull/140

**Comment by deksden** [comment]
Temporary solution (until this repo update) is to use my patched repo instead this original: 

```npm --save install deksden/sequelize-hierarchy```

**Comment by jeremyputeaux** [comment]
Same problem here. Planning on fixing this soon?

**Comment by bammoo** [comment]
Waiting for fix

**Comment by MilanMaric** [comment]
👍

**Comment by BrettStrongEH** [comment]
Deksden = Legend!

**Comment by deksden** [comment]
My fork updated with all recent fixes - see https://github.com/overlookmotel/sequelize-hierarchy/pull/143 for changes

**Comment by overlookmotel** [comment]
Fix is going to be merged very soon!

**Comment by overlookmotel** [comment]
Fixed in v1.3.2, just released. Very sorry this has taken so long to get to. I've been crazy busy.

And big up and maximum respect to @deksden for releasing a fork in the meantime.
