### ISSUE TITLE
Updating Hierarchy in afterUpdate hook instead of beforeUpdate hook?

### ISSUE THREAD

**Issue by harshkothari410** [overlookmotel/sequelize-hierarchy#145]
If you update anything in beforeUpdate Hook then then DB throws an error then in ancestor table that thing is updated which is not true for GET hierarchy request. So can we update ancestor table in afterUpdate instead of beforeUpdate ?

**Comment by overlookmotel** [comment]
Hi @harshkothari410.

Can you please post some example code that demonstrates the problem? It soundly like you have a genuine issue here, but I am having difficulty in understanding exactly what.

**Comment by overlookmotel** [comment]
ping @harshkothari410

**Comment by overlookmotel** [comment]
Hi @harshkothari410. Can you give some more details on this please?

**Comment by overlookmotel** [comment]
No response from OP, so closing this.
