### ISSUE TITLE
Overriding INSERT command with SELECT

### ISSUE THREAD

**Issue by Lahori-Jawan** [overlookmotel/sequelize-hierarchy#146]
versions:

`"sequelize"`: "^4.31.0",
`"sequelize-hierarchy"`: "^1.3.2",
`"sqlite3"`: "^3.1.13"

I am building comment system where comments have reply. before using this plugin, Comments are being stored correctly with respective ids and `parentIds` (for reply only) and for frontend disply I needed to get all replies (if any) of any comment in heirarchy form, which this plugin is made for. So I installed and did the respective adjustment in my code as the docs say and as soon as I create very first comment, it complains about `Parent does not exist`. My first impression was "How the very first comment is supposed to have parent?" then I looked at the `SQL` queries where instead of executing the `INSERT` command it executes this 

`SELECT hierarchyLevel FROM comments AS comment WHERE comment.id = -1;`

here is the relevant code:

```
const CommentModel = db.define(
	"comment",
	{
		message: STRING
	},
	{
		hierarchy: true
	}
);
```

````
`// create comment`
async function createComment(comment) {
	console.log("args ", comment);
	return await Comment.create(comment)
}
````
you can see the `console.log` output but right after it starts `SELECT`ing without `INSERT`ing the comment.

`sql console output`

![hierarchy](https://user-images.githubusercontent.com/7579344/35480134-e2b3b56a-0429-11e8-8648-289be338ffac.png)

Is it a bug or I am doing it wrong?

**Comment by overlookmotel** [comment]
Hi @Lahori-Jawan.

Root nodes (i.e. nodes with no parent) should have `parentId` set to `null`. Then it'll work.

In your example, you're using `-1` for `parentId` to signify no parent. So when you try to insert a comment with `parentId: -1`, it looks for a comment in the database with `id = -1`, doesn't find one, and so returns the `Parent does not exist` error.

Hope this makes sense.

**Comment by Lahori-Jawan** [comment]
Thanks. I will let you know once I try this. 

Although I should have mentioned this that I am using `graphQL` which behaves differently. So instead of this plugin or any other means to get all replies, I can recursively call the same thing with however depth I wish...

**Comment by overlookmotel** [comment]
OK cool. I wasn't aware that Sequelize worked with GraphQL - I'm clearly out of date.

You can use recursive calls on any database to read an entire hierarchy. The purpose of this module really is to allow reading an entire hierarchy with a single query.
