### ISSUE TITLE
snake_case in DB but CamelCase when I get it. How to do it in sequelize-hierarchy?

### ISSUE THREAD

**Issue by loatheb** [overlookmotel/sequelize-hierarchy#147]
in `sequelize` modal, I can define the `filed` to control what I want to.

```js
sequelize.define('foo', {
  fooBar: {
    type: DataTypes.STRING,
    field: 'foo_bar'
  }
})
```

that means I can store foo_bar in db, but get fooBar in `sequelize`. 

Now I find `sequelize-hierarchy` will auto create `hierarchyLevel` and `parentId` columns. How to configure it to make it like the above?

**Comment by loatheb** [comment]
finally I find this way: 

```js
    model.isHierarchy({
        levelFieldAttributes: {
            field: 'hierarchy_level'
        },
        foreignKeyAttributes: {
            field: 'parent_id'
        },
    });
```

**Comment by overlookmotel** [comment]
@loatheb Glad you found the solution! I assume you found the answer in the README.

**Comment by loatheb** [comment]
@overlookmotel  😅😅 Sorry to bother you.

At first I didn't understand the meaning of this field in README. I tried many times and finally looked at the source code to understand how to do it.

Thanks again.
