### ISSUE TITLE
Getting tree structure until a certain ID

### ISSUE THREAD

**Issue by NicTorgersen** [overlookmotel/sequelize-hierarchy#149]
I have two models: `Location` and `ItemWithLocation`.

**Location**
```js
 var location = sequelize.define('location', {
  id: {
    type: DataTypes.UUID,
    unique: true,
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4,
  },
  parentLocationId: {
    type: DataTypes.UUID,
    // https://github.com/overlookmotel/sequelize-hierarchy#initializing-hierarchy
    hierarchy: true,
  },
  countryId: DataTypes.UUID,
  title: DataTypes.STRING,
}, {
  tableName: 'locations',
})

location.hasMany('itemWithLocation')
```
**ItemWithLocation**
```js
var itemWithLocation = sequelize.define('itemWithLocation', {
  id: {
    type: DataTypes.UUID,
    unique: true,
    primaryKey: true,
    defaultValue: DataTypes.UUIDV4,
  },
  title: DataTypes.STRING,
}, {
  tableName: 'itemsWithLocation',
})

itemWithLocation.belongsTo('location')
```

I have three `Locations` currently:

```js
"locations": [{
    "id": "437dc528-051f-4688-80b8-5d82e4cd1639",
    "parentLocationId": null,
    "countryId": "020b2dcc-d7bc-49ac-add2-1c8f9e73f7da", // some random country
    "title": "Municipality",
    "hierarchyLevel": 1,
    "children": [
        {
            "id": "4d0923a7-da65-4f6f-90e1-ef850f4dacf1",
            "parentLocationId": "437dc528-051f-4688-80b8-5d82e4cd1639",
            "countryId": null,
            "title": "City",
            "hierarchyLevel": 2,
            "children": [
                {
                    "id": "4d6923a7-da65-4f6f-90e1-ef850f4dacf1",
                    "parentLocationId": "4d0923a7-da65-4f6f-90e1-ef850f4dacf1",
                    "countryId": null,
                    "title": "Place",
                    "hierarchyLevel": 3
                }
            ]
        }
    ]
}]
```

`Location` is a tree structure (one parent per item), and `ItemWithLocation` has any ID in this tree structure.

I am having problems wrapping my head around how to get a logical output; I don't care if I have the parent at the top level, or if I have the lowest child on the first level, I just want them nested logically so I can transform them into objects which can be used by Algolia to be hierarchically faceted.

I can get one level, but I am hardcoding it which is not ideal in the slightest.

```js
let locations = await models.location.find({
  where: {
    id: itemWithLocation.location.parentLocationId
  },
  include: [{
    model: models.location,
    as: 'descendents',
    hierarchy: true,
    where: {
      id: itemWithLocation.location.id
    }
  }]
})
```

This returns:

```json
"ItemWithLocation": {
    "location": {
        "id": "4d0923a7-da65-4f6f-90e1-ef850f4dacf1",
        "parentLocationId": "437dc528-051f-4688-80b8-5d82e4cd1639",
        "countryId": null,
        "title": "City",
        "hierarchyLevel": 2,
        "children": [
            {
                "id": "4d6923a7-da65-4f6f-90e1-ef850f4dacf1",
                "parentLocationId": "4d0923a7-da65-4f6f-90e1-ef850f4dacf1",
                "countryId": null,
                "title": "Place",
                "hierarchyLevel": 3
            }
        ]
    },
}
```
Modifying my initial query like so:
```js
let locations = await models.location.find({
  where: {
    id: itemWithLocation.location.id
  },
  include: [{
    model: models.location,
    as: 'ancestors',
  }]
})
```
also just returns one level down:
```json
"ItemWithLocation": {
    "location": {
        "id": "4d6923a7-da65-4f6f-90e1-ef850f4dacf1",
        "parentLocationId": "4d0923a7-da65-4f6f-90e1-ef850f4dacf1",
        "countryId": null,
        "title": "Place",
        "hierarchyLevel": 3,
        "ancestors": [
            {
                "id": "4d0923a7-da65-4f6f-90e1-ef850f4dacf1",
                "parentLocationId": "437dc528-051f-4688-80b8-5d82e4cd1639",
                "countryId": null,
                "title": "City",
                "hierarchyLevel": 2,
            }
        ]
    },
}
```

Adding `hierarchy: true` to the include greets me with the error `You cannot set hierarchy on 'location' without using the 'descendents' accessor`. Doesn't make sense to me, but that's not really a surprise.

Adding `hierarchy: true` to the root object in `.find()` returns `Parent ID 4d0923a7-da65-4f6f-90e1-ef850f4dacf1 not found in result set`.

**Comment by overlookmotel** [comment]
Sorry for slow reply.

I'm not sure that I quite get what you're trying to do. Is it that you have an `ItemWithLocation` and you want to get its location and all the locations in it's ancestry (i.e. the parent location, the parent location's parent, and so on)?

If so, your 2nd example should work:

```js
let locations = await models.location.find({
  where: {
    id: itemWithLocation.location.id
  },
  include: [{
    model: models.location,
    as: 'ancestors',
  }]
});
```

Since you already have the `Location` of the `ItemWithLocation`, you could also try:

```js
let locations = await itemWithLocation.location.getAncestors();
```

What is the `Location` of the `ItemWithLocation` that you are trying to find?

If these don't work, either it's a bug (I think unlikely as someone probably would have found it before and this is tested for) or your ancestry table is corrupted. For the latter case, you could try using `await Location.rebuildHierarchy()` (see [here](https://github.com/overlookmotel/sequelize-hierarchy#rebuilding-the-hierarchy)).

Let me know how you get on...

**Comment by overlookmotel** [comment]
Closing as no response from OP.

**Comment by NicTorgersen** [comment]
Hi, sorry for that. I can't quite remember how I solved it, but I did so there was no bug with your awesome library.
