### ISSUE TITLE
Sequelize v5

### ISSUE THREAD

**Issue by deksden** [overlookmotel/sequelize-hierarchy#151]
Are we ready for v5 of sequelize? Anybody tested new version with this plugin?

**Comment by overlookmotel** [comment]
@deksden Do you have any idea when Sequelize v5 is due to be released?

**Comment by deksden** [comment]
@overlookmotel : No idea, but beta9 is out and here is v5 milestone: https://github.com/sequelize/sequelize/milestone/18

**Comment by overlookmotel** [comment]
Sequelize v5 support in v2.0.0, just released.

Reason for the major semver bump is dropped support for Node 4 and 6 at the same time.
