### ISSUE TITLE
rebuild hierarchy problem with dynamic primaryKey

### ISSUE THREAD

**Issue by lukichev** [overlookmotel/sequelize-hierarchy#157]
On 1.2.0 there was a map by 'id' field and everything worked. 
https://github.com/overlookmotel/sequelize-hierarchy/blob/v1.2.0/lib/modelExtends.js#L166

But in ^1.3.0 it was changed to 
https://github.com/overlookmotel/sequelize-hierarchy/blob/master/lib/modelExtends.js#L166

The problem is if your `primaryKey` is not '**id**', but '**uuid**' as in my case - rebuldHierarchy is not working. It is stops after finding items with hierarchy level 1 (those without parent_id) and then on next step trying to access `item[primaryKey]` where primaryKey is '**uuid**'.

Take a look on this two lines: 
It returns object **{id: itemId, path: path}**
https://github.com/overlookmotel/sequelize-hierarchy/blob/master/lib/modelExtends.js#L195

And here it is trying to map by dynamic field that could be '**uuid**' like in my usecase: 
https://github.com/overlookmotel/sequelize-hierarchy/blob/master/lib/modelExtends.js#L166

**Comment by lukichev** [comment]
It is possible to fix this issue by simply changing `item[primaryKey]` to `item.id` like it was in 1.2.0 on this line https://github.com/overlookmotel/sequelize-hierarchy/blob/master/lib/modelExtends.js#L166

**Comment by overlookmotel** [comment]
Hi @lukichev.

Can you please post the code (inc model definition) that you're using which isn't working? I'm crazy busy right now, so if you can make it easy for me to replicate the error, I'll get this fixed faster.

Thanks!

**Comment by lukichev** [comment]
@overlookmotel, hello. Here it my model, where primary key is 'uuid':

`module.exports = function (sequelize, DataTypes) {
    const Account = sequelize.define('Account', {
        uuid: {
            type: DataTypes.UUID,
            primaryKey: true,
            defaultValue: DataTypes.UUIDV4,
        },
        parentId: {
            field: 'parent_id',
            type: DataTypes.UUID,
        },
        hierarchyLevel: {
            field: 'hierarchy_level',
            type: DataTypes.INTEGER,
            allowNull: false,
        },
        createdAt: {
            field: 'created_at',
            type: DataTypes.DATE,
            allowNull: true,
        },
    }, {
        tableName: 'accounts',
        timestamps: true,
        underscored: true,
        hierarchy: {
            levelFieldName: 'hierarchy_level',
            levelFieldType: DataTypes.INTEGER,
            foreignKey: 'parentId',
            throughKey: 'account_id',
            throughForeignKey: 'ancestor_id',
            through: 'accountAncestor',
            throughTable: 'accounts_ancestors',
        },
    });

    return Account;
};
`

**Comment by lukichev** [comment]
Beacause primaryKey here https://github.com/overlookmotel/sequelize-hierarchy/blob/master/lib/modelExtends.js#L166 is 'uuid', but result after first iteration is in **{id: itemId, path: path}** format I have such result on second iteration: **{ parentId: [ undefined ] }**.

**Comment by overlookmotel** [comment]
Thanks. Please can you post the data that you have in the table which you're trying to rebuild? And the code you are running to rebuild the hierarchy? (just want to make sure I'm not missing something)

**Comment by lukichev** [comment]
@overlookmotel, the table data is fairly simple. Just one parent account and some child accounts. 
I'm using method like this, nothing special: 
```javascript 
await models.Account.rebuildHierarchy();
```

**Comment by lukichev** [comment]
Any updates on this?

**Comment by overlookmotel** [comment]
@lukichev I'm really sorry but I'm away with work for next 2 weeks, so not going to get on this any time soon. Please feel free to submit a PR to fix it and I'll look at it when I return. Really sorry I can't do anything faster than that.

**Comment by erwzqsdsdsf** [comment]
![asd](https://user-images.githubusercontent.com/3872983/45000046-345a1500-aff4-11e8-86a7-69336278170f.png)

i fix this bug,
[https://github.com/erwzqsdsdsf/sequelize-hierarchy/commit/b27cc53d55a1a7734cd5da3c4da7ab9ffa76c581#diff-0d241ba769fd41d50bd211e1fbb9a823](url)

**Comment by lukichev** [comment]
@overlookmotel, I've created PR for this issue, please review. 
https://github.com/overlookmotel/sequelize-hierarchy/pull/159

**Comment by lukichev** [comment]
@overlookmotel any updates so far?

**Comment by lukichev** [comment]
@overlookmotel any estimates when PR will merged?

**Comment by overlookmotel** [comment]
This should be fixed in v2.0.3, just released. Please can you check and let me know if it's working?
