### ISSUE TITLE
does it will support multi user?

### ISSUE THREAD

**Issue by erwzqsdsdsf** [overlookmotel/sequelize-hierarchy#158]
every user has a independent  data scope。 Distinguish  by user id。

all function add a parm，used id。

**Comment by overlookmotel** [comment]
Sorry, I don't understand what you are asking. Please can you explain more clearly?

A code example would help.

**Comment by overlookmotel** [comment]
Closing issue as no response from OP.

**Comment by bravo-kernel** [comment]
I think the OP might be wondering about the same thing as me... would it be possible to use sequelize-hierarchy to create hierarchies for multiple users?

As an example:
- user A has her own folder hierarchy
- user B has her own folder hierarchy

Questions:
- can we use this plugin to store the hierarchies for both users A and B?
- can we use the same database tables (`folders` and `foldersancestor`)
- would that require adding a database field like `user_id` in one of those tables?
- if possible, what would be a good pointer to get us going?

Even though I have only just created my first parent and child node... love this plugin❤️

**Comment by bravo-kernel** [comment]
Hopefully someone can confirm but this looks very doable without any changes to the plugin:

- create a root node for each user
- fill the `name` field of the root node with user-id of the specific user
- scope user results to only the root node (and descendents) for that specific user

This worked for me in a scenario where I have two root nodes named `userA` and `userB`:

```js
  folders.isHierarchy()

  async function asyncCall() {
    let result = await folders.findOne({
      where: {
        name: 'userA'
      },
      include: {
        model: folders,
        as: 'descendents',
        hierarchy: true
      }
    })
    console.log(JSON.stringify(result, null, 4))
  }
  asyncCall()
```
Produces the following hierarchy owned by `userA`:

```json
{
    "id": "3be40090-6e07-4af7-8b31-4900912dab0c",
    "name": "userA",
    "createdAt": "2019-06-16T08:15:14.000Z",
    "updatedAt": "2019-06-16T08:15:14.000Z",
    "hierarchy_level": 1,
    "parent_id": null,
    "children": [
        {
            "id": "65b3190e-980f-43fc-a522-345bde807cd8",
            "name": "userA-child1",
            "createdAt": "2019-06-16T08:47:17.000Z",
            "updatedAt": "2019-06-16T08:47:17.000Z",
            "hierarchy_level": 2,
            "parent_id": "3be40090-6e07-4af7-8b31-4900912dab0c"
        }
    ]
}
```

ps: additional checks are probably needed to prevent users from changing hierarchies of other users.

**Comment by overlookmotel** [comment]
@bravo-kernel

Scope support is pretty dodgy. It was added in a PR from another person. I accepted the PR but it turns out the implementation they provided is incomplete/buggy and they've not responded to any of my requests for clarification/fixes. I don't use Postgres myself and so don't use or understand scopes, so I'm not able or motivated to fix it myself. And no-one else seems motivated either. So I'm afraid until someone steps up to do the work to figure it out and fix it, this is how it'll remain! Typical open source quandary...

Anyway, it sounds like you have found a solution for your problem that doesn't require scopes. Certainly if "user" doesn't mean anything special, and is just another database table, you shouldn't need scopes, so you should be able to implement it fine with this plugin as is.

Thanks for posting your solution for others to learn from.

**Comment by bravo-kernel** [comment]
Appreciate the compliment, no need for over-engineering if you ask me. For future reference... after making a small modification multi-user now works perfectly for me:

- no longer returns the root-node (created for the user automatically)
- only returns the descendents (self-created by the user) ❤️ 

```js
  folders.isHierarchy();

  // test hierarchy for a given root node/user-id
  async function asyncCall() {
    let result = await folders.findOne({
      where: {
        name: 'userA'
      },
      include: {
        model: folders,
        as: 'descendents',
        hierarchy: false // `true` to generate a nested/indented json response
      }
    });

    console.log(JSON.stringify(result.descendents, null, 4));
  }

  asyncCall();
```

Produces the following hierarchy, self-created by userA:

```json
[
    {
        "id": "2f2d48b6-aa70-4cbb-bbc9-3a643638dca9",
        "name": "userA-child2",
        "createdAt": "2019-06-16T09:05:00.000Z",
        "updatedAt": "2019-06-16T09:05:00.000Z",
        "hierarchy_level": 3,
        "parent_id": "65b3190e-980f-43fc-a522-345bde807cd8",
        "foldersancestor": {
            "folders_id": "2f2d48b6-aa70-4cbb-bbc9-3a643638dca9",
            "ancestor_id": "3be40090-6e07-4af7-8b31-4900912dab0c"
        }
    },
    {
        "id": "65b3190e-980f-43fc-a522-345bde807cd8",
        "name": "userA-child1",
        "createdAt": "2019-06-16T08:47:17.000Z",
        "updatedAt": "2019-06-16T08:47:17.000Z",
        "hierarchy_level": 2,
        "parent_id": "3be40090-6e07-4af7-8b31-4900912dab0c",
        "foldersancestor": {
            "folders_id": "65b3190e-980f-43fc-a522-345bde807cd8",
            "ancestor_id": "3be40090-6e07-4af7-8b31-4900912dab0c"
        }
    },
    {
        "id": "7af308f1-43f8-4e4b-b074-490ed2ff2e40",
        "name": "userA-child2",
        "createdAt": "2019-06-16T09:33:01.000Z",
        "updatedAt": "2019-06-16T09:33:01.000Z",
        "hierarchy_level": 3,
        "parent_id": "65b3190e-980f-43fc-a522-345bde807cd8",
        "foldersancestor": {
            "folders_id": "7af308f1-43f8-4e4b-b074-490ed2ff2e40",
            "ancestor_id": "3be40090-6e07-4af7-8b31-4900912dab0c"
        }
    }
]
```

**Comment by overlookmotel** [comment]
If each user has one folder hierarchy, you could also add a field `folderId` on the `User` model that points to that user's folders. Then:

```js
User.findOne( {
  where: {id: userId},
  include: {
    model: Folder,
    include: {
      model: Folder,
      as: 'descendents'
    }
  }
} );
```

Yes, you'd need to make sure one user can't alter folders that don't belong to them. But that's outside of the scope of this plugin.

**Comment by bravo-kernel** [comment]
Awesome, thanks again for your input, highly appreciated 💯
