### ISSUE TITLE
Error if i hide node

### ISSUE THREAD

**Issue by ivan-ionin** [overlookmotel/sequelize-hierarchy#160]
I have a some tree:

PostgreSQL:
A
... A.1
... A.2
... A.3 (hidden: true)
...... A.3.1
...... A.3.2
...... A.3.3

And all my nodes have property "hidden" (true/false).

Now i want select all nodes without hidden:true, like this:

`
('MySweetTree').findAll({where: {hidden: false}, hierarchy: true})...
`

And i got error:

**Unhandled rejection SequelizeHierarchyError: Parent ID (A.3) not found in result set**

Because node A.3 is hidden! Please, do something :(((

**Comment by overlookmotel** [comment]
Hi.

The reason for this error is that it fetches all the nodes with `hidden: false`, then it moves each node to that of its parent. So if A.3.1 has `hidden: false`, it has been fetched but `A.3` (its parent) has not. So it cannot find the parent.

The solution is that when you mark as node as hidden, you need to mark all its children and chidren's children hidden too.

I would be open to a PR for suppressing the error message if a certain option is set.

Closing this issue now as I feel it's answered, but feel free to come back to me if you want to discuss further.

**Comment by Djalmar** [comment]
any news on that PR ?
same issue here

**Comment by overlookmotel** [comment]
@Djalmar Maybe submit a PR yourself?
