### ISSUE TITLE
Needs table in database

### ISSUE THREAD

**Issue by zeeshanjan82** [overlookmotel/sequelize-hierarchy#17]
As per the readme on the following line
```html
Creates a new model folderAncestor which contains the ancestry information
```
I am getting a sequelize error stating that the table folderAncestor does not exist in the database. 

I am getting following error:
````js
    "name": "SequelizeDatabaseError",
    "message": "ER_NO_SUCH_TABLE: Table 'folderancestors' doesn't exist",
````

**Comment by zeeshanjan82** [comment]
Also does it require to have the column HierarchyLevel present in the database. As per my understanding this column will be dynamically added.

**Comment by zeeshanjan82** [comment]
was able to fix the issue by using children instead of descendants in the query.

**Comment by Aralizer** [comment]
Hi,

I'm currently encountering a similar issue.
Went exactly by the examples in the readme file
This example - 
```
 // get entire hierarchy as a nested tree
folder.findAll({ hierarchy: true })
```
works as expected, but the next one 
```
// get all the descendents of a particular item
folder.find({
    where: { name: 'a' },
    include: {
        model: folder,
        as: 'descendents',
        hierarchy: true
    }
)
```

Fails with this error
```
"name": "SequelizeDatabaseError",
"message": "ER_NO_SUCH_TABLE: Table 'folderancestor' doesn't exist"
```

Another attempt with the result of the first (successful) example was to use the `getDescendents()` method. This resulted with the same error

I'm using all default values, names and options - `folder.isHierarchy()` only.
MySQL, sequelize 3.30.4 (latest 3.x)

Do I actually need to create this table before hand...?
What am I missing here?
