### ISSUE TITLE
many roots 

### ISSUE THREAD

**Issue by u-can-miracle** [overlookmotel/sequelize-hierarchy#179]
Is it possible to make hierarchy with many roots?
```
Root 1
    Child 1.1
    Child 1.2

Root 2
    Child 2.1
    Child 2.2
```
And separate them in result by query somehow and get such result
```
 Root 1
    Child 1.1
    Child 1.2
```
separately from `Root 2`

**Comment by bravo-kernel** [comment]
You may want to read this issue. https://github.com/overlookmotel/sequelize-hierarchy/issues/158

**Comment by overlookmotel** [comment]
@bravo-kernel is right. This is perfectly possible. Please see #158.
