### ISSUE TITLE
How can I use `thisFolder.getAncestors()` inside a getter?

### ISSUE THREAD

**Issue by diosney** [overlookmotel/sequelize-hierarchy#20]
Hi!

I want to add a virtual attribute defined as:

```js
ancestors : {
    type: orm.Sequelize.VIRTUAL,
    get: function() { return 'TODO how return getAncestors here?' }
  }
```

I tried several things and none worked, is this even possible or do I have to get a model instance previously?

Thanks

**Comment by diosney** [comment]
Any ideas on this?

I need this to send an ancestors array in each API endpoint that returns the model.

Thanks

**Comment by overlookmotel** [comment]
Hi @diosney. I'm afraid this isn't possible. You'd need to load the ancestors first with `include`. A getter can't execute asynchronously, and therefore can't fetch the ancestors from the database. When you use `include`, it fetches them at the same time as the main query.

This is a limitation of Sequelize (actually I think quite a reasonable one). I'm afraid there's nothing I can do about it, so am closing this PR.
