### ISSUE TITLE
A way to fetch Descendants up to a particular level.

### ISSUE THREAD

**Issue by yaldram** [overlookmotel/sequelize-hierarchy#208]
Hello Sir, Thanks a lot for this awesome plugin.  I am using your plugin and really love the way it works.
I just have a question though. Please have a look at the below image : -

![Fileone](https://user-images.githubusercontent.com/13429535/73939996-9d903700-4910-11ea-9961-6edb924e2592.png)

Here I am showing Direct Reports, where I can fetch **All Descendants of a user**, simple enough, but let us assume there are hundreds of users below me and I am a manager, I don't want to fetch all of them at once. 

So my approach was to click on the plus and fetch the **children** rather than the **descendants**. Now if I click on **Micheal** I get its children but if any of them further has children I have no idea about that. So this approach kind of fails.

So my second approach was to fetch, children only 2 levels deep, if I click on **Micheal** I will get descendants up to 2 levels and when I click on **Micheal's** direct descendant I will get next 2 levels and so on. Like so : -

![FileTwo](https://user-images.githubusercontent.com/13429535/73940008-a2ed8180-4910-11ea-9970-40bed92b853b.png)

I just wanted to ask can I fetch **Descendants only up to 2 levels deep** using **sequelize-hierarchy**. If not please suggest your approach. Thanks a lot.

**Comment by yaldram** [comment]
**Got it : -**

```javascript
await Users.findOne({
    where: { id: userId },
    include: [
      {
        model: Users,
        as: "allEmployees",
        hierarchy: true,
        where: {
          [Sequelize.Op.or]: [
            {
              hierarchy_level: hierarchy_level + 1
            },
            {
              hierarchy_level: hierarchy_level + 2
            }
          ]
        },
        attributes: { exclude: ["created_at", "updated_at"] }
      }
    ],
    order: [
      [
        {
          model: Users,
          as: "allEmployees"
        },
        "hierarchy_level"
      ]
    ],
    attributes: { exclude: ["created_at", "updated_at"] }
  });

```

**Comment by overlookmotel** [comment]
Sorry I never replied. Glad you figured it out!
