### ISSUE TITLE
Update error if parent deletedAt not null

### ISSUE THREAD

**Issue by dronowar** [overlookmotel/sequelize-hierarchy#218]
Try to update record with deleted parent 
await Comment.update(commentData, { where: {id: id}, silent: false, paranoid: false});

`Executing (default): SELECT "id", "parentId", "hierarchyLevel" FROM "comments" AS "comment" WHERE ("comment"."deleted
At" IS NULL AND "comment"."id" = '2');
Executing (default): SELECT "hierarchyLevel", "parentId" FROM "comments" AS "comment" WHERE ("comment"."deletedAt" IS
 NULL AND "comment"."id" = 1);
(node:5196) UnhandledPromiseRejectionWarning: SequelizeHierarchyError: Parent does not exist
    at Function.beforeBulkUpdate (....\node_modules\sequelize-hierarchy\lib\hooksModel.js:312:23)`

**Comment by overlookmotel** [comment]
Possibly related to #71.

**Comment by overlookmotel** [comment]
You cannot have a node with a deleted parent. It doesn't make sense because you're saying "this is my parent" but that parent doesn't exist. If you delete the parent you must unlink the children from it first.

Does that make sense?

**Comment by dronowar** [comment]
I use softdelete in the comments. It so happens that one comment was deleted (deletedAt not null), for example for a violation by admin, but the whole branch below it should remain.
In my specific case, I can ignore this situation and do not need to move the branch.
In fact, the parent comment is not deleted, but simply marked as prohibited deletedAt
And I was hoping that passing {paranoid: false} would not cause the “deleted At” IS NULL in SQL

**Comment by overlookmotel** [comment]
I'm sorry but this usage is pretty out of the ordinary and I don't think it should be supported.

I'd suggest using your own field `isProhibited` (or something) and toggling that on and off if you want to remove comments from view.

`deletedAt` is meant to indicate that the row is essentially deleted and queries should act as if it's not there, which is what this plugin does.

I hope the suggested workaround can solve this for you.
