### ISSUE TITLE
Stop Using Ancestors

### ISSUE THREAD

**Issue by LucasBremm** [overlookmotel/sequelize-hierarchy#220]
Hi, I have a project using your awesome module, but I don't want to use the ancestor/descendant thing, its not usefull for my case and I do not want to create a sql table for that. When I try to add a new row I get this error: 
- Table 'database.tableancestors' doesn't exist

I don't want to create and use this functionality, is there a way to turn it off?

**Comment by overlookmotel** [comment]
Hi. I'm afraid I don't really understand. You say "I don't want to use the ancestor/descendant thing" but that is the whole essence of this package! If you don't want it, you'd have no use for this package.

What I mean by this is: The ancestors table is what allows you to fetch an entire nested tree in one query. It tracks the ancestry of every node in the tree, so you can make queries which basically say "give me all the nodes in the tree below this one, and structure it as a tree". The first part of that is equivalent to "find all the nodes this node is an ancestor of".

So to do what this package does, it requires the data in the ancestors table. If you delete the ancestors table, it will break.

I hope that makes sense.

**Comment by LucasBremm** [comment]
What I meant was that I want to use the parent-children functionality, being able to get the parent of a object and the children of one object, but I don't need a query that requests all the ancestors or descendants of an object, and that I am forced to create another table just for that to work. But if that's not possible, than ok, no problem. Sorry for the trouble :)

**Comment by overlookmotel** [comment]
Hi again. Ah. Well in that case you don't need this package at all. You can do that just with Sequelize alone.

Just set up a parent-child "BelongsTo/HasMany" association in the same way you set up any other kind of association. You can link the same model to itself. Each node would have a `parentId` field which gives the `id` of its parent, or `null` if it's the root of the tree.

Please see here: https://sequelize.org/v5/manual/associations.html

**Comment by LucasBremm** [comment]
Oh, Ok, my fault then. Sorry to bother, and thank you very much for the help!
