### ISSUE TITLE
Multiple Ancestors/Parents

### ISSUE THREAD

**Issue by cdkirkwood** [overlookmotel/sequelize-hierarchy#224]
Hi, I'm wondering if it is possible for a descendent to have multiple ancestors. I essentially need to accomplish something like this:
          a
         /  \
       b    c
        \    /
          d
Not sure if this is possible with this library as I see that the setters `addAncestor` and `addDescendent` don't seem to work. Would greatly appreciate any clarity or insight

**Comment by overlookmotel** [comment]
Hi @cdkirkwood. I'm sorry but this package is only meant to handle tree-like hierarchies where each node has only 1 parent.

Please see this issue for a longer explanation: https://github.com/overlookmotel/sequelize-hierarchy/issues/98

**Comment by cdkirkwood** [comment]
Gotcha. Thank you for the quick response!
