### ISSUE TITLE
HierarchyError when limiting the number of results (pagination)

### ISSUE THREAD

**Issue by fruityfred** [overlookmotel/sequelize-hierarchy#30]
Hi,

I'm trying to implement a pagination system on a table that uses SequelizeHierarchy (v0.5.5). When limiting the number of results returned by Sequelize, Hierarchy throws an error:

> Unhandled rejection SequelizeHierarchyError: Parent ID 75 not found in result set

Of course, I understand this error: depending on the ordering of the entities, the parent may not be present in the results, and thus the `convertHierarchy()` method cannot find it.

How can I achieve this? Is this possible to have an option to simply ignore items whose parent is not in the results?

I tried this in *hooksUniversal.js* on line 183:
```javascript
if (!parent) return;
```
Instead of throwing an exception and, well, it worked fine for me.

Thank you very much for your work! And for your answer ;)

**Comment by overlookmotel** [comment]
Ah yes. I think the way to do this is...

Rather than:

```js
model.findAll( {
    limit: 20,
    hierarchy: true
} )
```

Try:

```js
model.findAll( {
    limit: 20,
    include: [ {
        model: model,
        as: 'descendents',
        hierarchy: true
    } ]
} )
```

That will give you the first 20 entries (i.e. page 1) + all the descendent hierarchy of those 20 (no matter how big they are).

Is that what you were trying to achieve?

**Comment by fruityfred** [comment]
Sorry for the delay, I had to work on some other projects in between...
I think this can work, I'll try later.

Thank you very much!
