### ISSUE TITLE
Supporting tables and fields not being created

### ISSUE THREAD

**Issue by joshuadmatthews** [overlookmotel/sequelize-hierarchy#31]
I want to implement this on a production app and I can't sync my database to my models anymore, instead I have to use migrations. It doesn't specify anywhere what the final tables need to look like to implement the migrations. Please provide this info.

**Comment by overlookmotel** [comment]
I've updated the README to give a few more details. See the section '`folder.isHierarchy()` does the following:'

But to make sure you get it right for your particular setup, including making all the right foreign key constraints, there's really no substitute for running `.sync()` on a development machine.

I hope this helps.
