### ISSUE TITLE
bug: beforeUpdate hook not work with  tables with schema

### ISSUE THREAD

**Issue by baltov** [overlookmotel/sequelize-hierarchy#46]
when the base table has own schema, in hook beforeUpdate that schema is not used.
result: on entity update: sql error unknown relation TABLE_NAME
my patch: 
file: lib/hooksModel.js
row 148:
<code>
sql = utils.replaceTableNames(sql, {through: hierarchy.through}, sequelize);
</code>
change to
<code>
sql = utils.replaceTableNames(sql, {through: hierarchy.through, item:model}, sequelize);
</code>

remove row 151
<code>
	151: -- item: model.tableName,
</code>

**Comment by overlookmotel** [comment]
Hi @baltov.

Thanks for spotting the bug. Would you mind submitting your fix as a PR? If you can write a test too that'd be even better! I don't use Postgres so schemas are rather out of my area of knowledge...

**Comment by overlookmotel** [comment]
Finally got around to fixing this. It's in v0.6.0.
