### ISSUE TITLE
Adding a filter condition to a child converts outer to inner join

### ISSUE THREAD

**Issue by mohitgp** [overlookmotel/sequelize-hierarchy#47]
I have folders model implemented using hierarchy = true. I also have a file which is a child model of the folder. See below

```
sequelize.define(Folder, 
  {
    name: {allowNull: false, type: DataTypes.STRING},
  },
  {
    classMethods: {
      associate: function(models) {
        Folder.hasMany(models.File);
        Folder.isHierarchy();
      }
    }
  });
```

File Model:
```
sequelize.define('Cleansheet', {
    name: {allowNull: false, type: DataTypes.STRING},
    status: DataTypes.STRING // used to mark deletion status
  });
```

To get a hierarchy of folders and files properly I use the following query which works fine
```
Folder.findAll({
  attributes: ['id', 'name', 'tags', 'status', 'updatedAt', 'parentId', 'hierarchyLevel']
  , order: 'updatedAt DESC'
  , include: {
    attributes: ['id', 'name', 'tags', 'updatedAt', 'shouldCost', 'status']
    , order: 'updatedAt DESC'
    , model: Cleansheet}, hierarchy: true })
```

But, if I delete a file I soft delete by marking status as "InActive". And to get only the Active files in the proper hierarchy I add where clause like below

```
Folder.findAll({
  attributes: ['id', 'name', 'tags', 'status', 'updatedAt', 'parentId', 'hierarchyLevel']
  , order: 'updatedAt DESC'
  , include: {
    attributes: ['id', 'name', 'tags', 'updatedAt', 'shouldCost', 'status']
    , **where: {status: {$ne: 'InActive'}}**
    , order: 'updatedAt DESC'
    , model: Cleansheet}, hierarchy: true })
```

Now the problem is the **left join between folder and file changes to inner join** which hides any empty folders. Please let me know if I am missing something here.

**Comment by overlookmotel** [comment]
Hi @mohitgp.

This is standard `sequelize` behaviour, actually nothing to do with `sequelize-hierarchy`. It'd be the same without using `hierarchy: true`.

When you add a `where` clause to an include, it makes the join into an `INNER JOIN`. To prevent this, set `required: false` as an option of the include.

Hope that helps.

Closing this issue as I don't think this actually relates to `sequelize-hierarchy`.

**Comment by mohitgp** [comment]
Thanks a lot. Yes, It worked.
