### ISSUE TITLE
SequelizeHierarchyError ParentId not found in result set

### ISSUE THREAD

**Issue by shriramshankar** [overlookmotel/sequelize-hierarchy#49]
I have a folder structure and all folders have a soft delete option. While fetching the hierarchy I want to fetch folders that are not deleted. I filter on the folder to get the one that is not soft deleted and I get  "SequelizeHierarchyError ParentId not found in result set" when at least one of the folders in the hierarchy is soft deleted.

**Comment by overlookmotel** [comment]
Hi @shriramshankar.

A very similar issue has been raised before. Please see here: https://github.com/overlookmotel/sequelize-hierarchy/issues/44

In short, I'm afraid there's not a simple way to deal with it.

**Comment by shriramshankar** [comment]
@overlookmotel Ok, Thanks.
