### ISSUE TITLE
`hierarchyLevel` will be null is the model has defined `beforeCreate` hook

### ISSUE THREAD

**Issue by luin** [overlookmotel/sequelize-hierarchy#5]
See pull request #6. All tests related to `hierarchyLevel` fails.

**Comment by overlookmotel** [comment]
It appears that this was due to a bug in sequelize which has now been fixed. On latest version of sequelize-hierarchy (v0.2.11) and sequelize (v2.1.0), adding a hook in model definition does not break any of the tests any more.

Sorry this took me so long to get round to...
