### ISSUE TITLE
Document and test `onDelete` option

### ISSUE THREAD

**Issue by overlookmotel** [overlookmotel/sequelize-hierarchy#50]
As discussed in https://github.com/overlookmotel/sequelize-hierarchy/issues/48

**Comment by overlookmotel** [comment]
Also could add to the docs the procedure for deleting a node and all its children.

**Comment by deksden** [comment]
Some work is done in this PR: https://github.com/overlookmotel/sequelize-hierarchy/pull/131

**Comment by overlookmotel** [comment]
Done in v2.0.4.
