### ISSUE TITLE
through associations do not work.

### ISSUE THREAD

**Issue by antoxi4** [overlookmotel/sequelize-hierarchy#51]
My code is 
```javascript
through: 'UserAncestor',
    throughTable: 'intrist_user_users',
    throughForeignKey: 'parentId',
    throughKey: 'userId',
```

we need manyToMany hierarchy through table.

**Comment by overlookmotel** [comment]
Hi @antoxi4.

Could you provide some more details? Like your model definitions and what problem is occurring?

I'd like to investigate, but I'm not clear at this point exactly what you're trying to achieve and what problem you're facing.

**Comment by kopylash** [comment]
We have User model with many-to-many relationship through table. Now we need to handle hierarchy of different levels, for instance, one User can have many children and can have many parents, which also can have many parents, etc.
User model: https://gist.github.com/antoxi4/784165609efe28d06984eda5e9bbb2d4
UserAncestor model: https://gist.github.com/antoxi4/429a3b9111e4b81595a30eafdf2675eb

**Comment by overlookmotel** [comment]
@kopylash Ah I see. I'm afraid this module doesn't support that. The structure you're talking about is more like a graph than a tree, which wasn't what this module was designed for.

In a tree structure, each node can have multiple children but only one parent.

I suppose this module could be adapted to support many pareents, but I think it'd be too far from the main functionality. Based on the principle of a module "doing one thing, and doing it well", I think it'd be better for this module to stay focused to the existing function, and for another module to cover this case.

There's probably something out there already on npm which can be adapted to your needs.

Sorry I can't be more helpful.
