### ISSUE TITLE
Bill of materials model implementation

### ISSUE THREAD

**Issue by asaf050** [overlookmotel/sequelize-hierarchy#52]
The models you linked fail to address some major properties BOMs normally have:

- Parts and sub-assemblies can be reused. For example, it is common for a same kind of bolt to be used in many assemblies.
- There needs to be a BOM-specific quantity. For example, it's important to know that one assembly needs (say) 50 bolts, but the other assembly might only need 30 of the same kind of bolt.

![wn9gv](https://cloud.githubusercontent.com/assets/7129342/14913872/c6b683f0-0e0e-11e6-9831-7c5bada15e78.png)

Is it possible to implement this model with `sequelize-hierarchy`?

**Comment by overlookmotel** [comment]
No I'm afraid this isn't supported. This module is for building hierarchical tree structures where each node has only 1 parent. In your BOM scheme, this would mean each part can only be used in one place. This module wasn't intended as a BOM implementation, more for representing file system-like folder structures.

You can build all of your BOM example in sequelize using many-to-many joins - you don't need sequelize-hierarchy fro that. But you just can't use sequelize-hierarchy to then trace ancestry (e.g. query "tell me all the parts and parts of parts and parts of parts of parts in this assembly").

I'm afraid there's no plan to change this module to support BOM-type structures. It's just not the intended function of this module, and I think would be better implemented in another library.
