### ISSUE TITLE
Order by level wise

### ISSUE THREAD

**Issue by pravinohal** [overlookmotel/sequelize-hierarchy#69]
Hi,
   Is there any way in sequelize-hierarchy to have different orderings for each level
I'm using "sequelize-hierarchy": "^0.5.8". Thanks in advance

```js
[//1st level
  {
  "id": 2,
  "firstName": "abc",//**order by firstName**
  "lastName": "Jackson", 
  "email": "sdf@gmail.com"
   "children":[   // 2nd level
           { 
                  "id": 2,
                   "firstName": "bbb",
                    "lastName": "Jackson",//**order by lastname**                     
                      "email": "sdf@gmail.com"
                       "children":[   // 3rdlevel
                                      { 
                                          "id": 2,
                                             "firstName": "ccc",
                                             "lastName": "Jackson",                                             
                                                "email": "sdf@gmail.com"//**order by email** 
                                            }
      ]
           }
      ]
}
]
```

**Comment by overlookmotel** [comment]
@pravinohal I'm afraid I don't understand what you're trying to do.

Could you please post the model definitions and kind of query you'd like to run?

i.e.:
```js
sequelize.define('Person', { ... } );

Person.findAll( { include: { ... } } );
```

**Comment by overlookmotel** [comment]
Also, there was a bug with ordering which was recently fixed. So probably a good idea to upgrade to latest version of sequelize-hierarchy.

**Comment by pravinohal** [comment]
@overlookmotel  thanks for your quick response. Following are the required details you  need
**Defination**
module.exports = function(sequelize, DataTypes) {
  var Post = sequelize.define('post', {
    details: {
      type: DataTypes.STRING(400),
      allowNull: false
    }
    acceptedAnswer: {
      type: DataTypes.BOOLEAN,
      allowNull: false,
      defaultValue: 0
    }
    upVotes: {
      type: DataTypes.INTEGER,
      allowNull: false,
      defaultValue: 0
    },
    projectId: {
      type: DataTypes.INTEGER,
      references: 'project', //  its table's name, not object name
      referencesKey: 'id' //  its a column name for foreign key
    }
  }, {
    freezeTableName: true
  });
  Post.isHierarchy();
  return Post;
};


db.post.findAll({
      attributes: ["id", "details", "postTypeId", "projectId", "parentId",
        "acceptedAnswer", "isResolved", "upVotes", "downVotes", "createdAt",
        "updatedAt", "postBlurb", "createdBy", "updatedBy"
      ],
      hierarchy: true,
      as: 'descendents',
      where: {
        projectId: projectId
      },
      order:??? 
    })

Here I'm trying to get all the hierarchical records in a Post.
1. At the first level I'll get all records of type topic. But these records should be ordered by postid
2. At the second level i.e children of topics I'll get all records of type challenge, But these records should be ordered by isRosolved.
3. At the third level i.e children of challenge I'll get all records of type suggestion, But these records should be ordered by acceptedAnswer, upvotes.

I've got all the records level wise except for the ordering for each level.
Can you please let me know can this be achieved through sequelize-hierarchy? if yes how can it be done.

**Comment by overlookmotel** [comment]
Ah OK. I get what you're after now. You don't actually need sequelize-hierarchy for this at all. Just plain sequelize will do it.

Just add a `parentId` field to the model, and then make it a self-reference to Post with:

```js
Post.hasMany( Post, {as: 'children', foreignKey: 'parentId'} );
```

Then:

```js
Post.findAll( {
    where: {
        projectId: projectId,
        parentId: null
    },
    include: {
        model: Post,
        as: 'children',
        include: {
            model: Post,
            as: 'children'
        }
    },
    order: [
        ['id'],
        [{model: Post, as: 'children'}, 'isResolved'],
        [{model: Post, as: 'children'}, {model: Post, as: 'children'}, 'acceptedAnswer']
    ]
} );
```

I may not have the example above 100% right, but if you read the Sequelize docs you should be able to work it out from here.

A couple of other pointers:

1. When you post code in Github issues it helps if you surround it with "```". The code then is presented with indentation which makes it much easier to read. I edited your 2 posts above to add "```" and you can see it makes it much clearer. If you don't know what I'm talking about, just click the edit (pencil) item on one of your posts above and have a look.

2. Your database scheme might work better if you had 3 different models called `Topic`, `Challenge` and `Suggestion` since these seem to be different things in your post above. Depending on other factors which I don't know about, this may be a bad suggestion. But maybe worth thinking about.

**Comment by overlookmotel** [comment]
Hope the above is some help.

Closing this issue as it doesn't relate to sequelize-hierarchy.
