### ISSUE TITLE
Updating to latest Sequelize pre-release

### ISSUE THREAD

**Issue by maxwallasaurus** [overlookmotel/sequelize-hierarchy#79]
Hello, 

I just upgraded my Sequelize to the latest pre-release (v4.0.0-1). I now get the following error when trying to declare my hierarchy models: 

`TypeError: model.isHierarchy is not a function` 
    `at Sequelize.module.exports.afterDefine (C:\Users\mwall\Documents\inventory\node_modules\sequelize-hierarchy\lib\hooksUniversal.js:46:24)
`

This error is thrown regardless of whether I use `Model.isHierarchy()` or `sequelize.define("model", attributes, { hierarchy: true });`

If possible, can you advise on how to get around these errors? I need to use the latest pre-release of sequelize for a specific bugfix, so downgrading isn't really a possibility. 

Thanks in advance. 
Cheers, 
Max

**Comment by overlookmotel** [comment]
@maxwallasaurus sequelize-hierarchy doesn't support sequelize v4.x yet.

v4.x changes how models inherit properties from `Sequelize.Model` (see https://github.com/sequelize/sequelize/pull/5924). So that's probably what's breaking it. Probably not a difficult fix, but I don't have time right now - and was planning on waiting till v4.0.0 is released to work on it.

If you'd like to investigate and submit a PR, please feel free.

**Comment by maxwallasaurus** [comment]
@overlookmotel Thanks for the response. I would be psyched to submit a PR. Will look into it right now.
Best, 
Max

**Comment by overlookmotel** [comment]
OK great. Thanks. NB the module still needs to work for Sequelize v2.x and v3.x. So any changes that need to be made for v4.x but which aren't backward compatible should be implemented in `lib/patches.js` with alternative versions for v2/3 and v4. I hope that makes sense...

**Comment by overlookmotel** [comment]
Version 0.8.0 just released works with Sequelize v4 pre-release (v4.0.0-2).

Well at least it *seems* to work - all the tests pass, but the tests don't have complete coverage of all options and for the many possible options that can be set within sequelize too.

@maxwallasaurus Can you please try it out and let me know if you run into any problems or not?

**Comment by maxwallasaurus** [comment]
Absolutely! Thanks. Sorry for the radio-silence. I tried my hand at a PR but couldn't figure it out... then I  went on honeymoon... Will let you know if this works for us.

Thanks again.

**Comment by maxwallasaurus** [comment]
This worked out great for us. Thanks so much for supporting the pre-release. 

Cheers, 
Max
