### ISSUE TITLE
Getting raw data nested with sequelize-hierarchy

### ISSUE THREAD

**Issue by bloodhawk** [overlookmotel/sequelize-hierarchy#9]
I'm having issues getting raw data to nest properly. Are there any known issues with this? An example query is as follows:

```
models.centers.findAll({hierarchy: true, include: [{ 
  			model: models.reports, 
  			as: 'Reports', 
  			attributes: [
  				'id', 
  				'visitor_total', 
  				'visitor_tour', 
  				'visitor_tournonmember', 
  				'referral_cards', 
  				'referral_called', 
  				'referral_inbound', 
  				'referral_member',
  				'comments',
  				[Sequelize.fn('date_format', Sequelize.col('Reports.date'), '%Y-%m-%d'), 'date']
  			]
  	  	}]
	}).then(function(results){  });
```

With this query I'm getting a bunch of locations. Locations can have child locations, and the locations themselves have reports I need to get at. So the parent location will have reports and the child sites will have reports. 

However with the query like this I get all the instances etc. Doing this I use map to generate a new object with the data I actually need. However, if I try to use the options ```raw: true``` and ```nest: true``` I get errors. Am I able to use these options successfully with sequelize-hierarchy and still get the nested relationship? My main goal is to simply get the raw JS objects formatted without having to do all the dirty work myself (let dottie basically do it within Sequelize).

**Comment by overlookmotel** [comment]
Sorry for very slow reply. My day job has been crazy past few months and I haven't had any time to maintain these plugins.

I'm afraid using the option `raw: true` isn't supported in conjunction with `hierarchy: true`. This plugin relies on information in the instances returned to construct the hierarchy. It would require quite a major re-write to make it work, and I'm afraid I don't have time to do that at the moment.

But I'll leave this issue open as a reminder to me to look at implementing it at some point in the future.

In the meantime, to make it easier to get the raw data you can use:

```js
var rawInstance = instance.get({plain: true});
```

This returns the raw data for the instance and also all nested instances (including the hierarchy) - easier than traversing the whole nested tree of includes in your own code.

Sorry not to be able to be more help at the moment...

**Comment by overlookmotel** [comment]
@bloodhawk Finally got round to implementing this! Is supported in v0.5.3.

**Comment by bloodhawk** [comment]
Very cool. Thanks for your hard work.
